name: qmixer_grcn
embedding_dim: 32
hyper_w1: {number_of_layers: 2, hidden_size: 32, activation: ReLU, activation_after_last_layer : False}
hyper_final: {number_of_layers: 2, hidden_size: 32, activation: ReLU, activation_after_last_layer : False}
#state dependent bias for last layer
V:  {number_of_layers: 2, hidden_size: 32, activation: ReLU, activation_after_last_layer : False}

mixer: {number_of_layers: 2, hidden_size: 128, activation: ReLU, activation_after_last_layer : False}

defaults:
  - /agent/model@state_embedding: ddqn/grcn