name: grcn
is_rnn: False
grcn:
  rnn: False
  resource_embedding_dim: 512
  q_net : {hidden_size : 512, number_of_layers: 4, activation: ELU, activation_after_last_layer : False}
  resource_embedding_net : {hidden_size : 512, number_of_layers: 4, activation: ELU}
  use_nn_scaling : True
  scaling_net: { hidden_size: 128, number_of_layers: 2, activation: Sigmoid }
