name: grcn_twin_att
is_rnn: False
grcn:
  resource_and_scaling_agent_specific: False
  rnn: False
  resource_embedding_dim: 256
  agent_embedding_dim: 256
  action_embedding_net: {hidden_size : 256, number_of_layers: 2, activation: ReLU}
  q_net : {hidden_size : 256, number_of_layers: 2, activation: ReLU, activation_after_last_layer : False}
  agent_embedding_net : {hidden_size : 256, number_of_layers: 2, activation: ReLU}
  resource_embedding_net : {hidden_size : 256, number_of_layers: 2, activation: ReLU}
  use_same_network_for_other_agents_resoruce_embeddings: True
  distance_matrix_only_single_distance: False
  layer_norm: False
  other_agent_after_q: False
  normalization_type: softmax
  multiply_with_other: False
  learnable_other_weight: True
  use_nn_scaling : True
  add_distance_to_action : True
  att_per_edge_num_heads: 4
  scaling_net: { hidden_size: 512, number_of_layers: 2, activation: Sigmoid }
  action_specific_bias: False
  use_one_hot_id: True
  other_agent_reduction: sum
